apiVersion: v1
kind: Service
metadata:
  name: groupe9-mongo-svc
  namespace: groupe9-alone
spec:
  selector:
    app: groupe9-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

