apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupe9-mongo-deployment
  namespace: groupe9-alone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: groupe9-mongodb
  template:
    metadata:
      labels:
        app: groupe9-mongodb
    spec:
      containers:
      - name: groupe9-mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: groupe9-mongo-storage
          mountPath: /data/db
      volumes:
        - name: groupe9-mongo-storage
          persistentVolumeClaim:
            claimName: groupe9-mongo-pvc

