apiVersion: v1
kind: Service
metadata:
  name: groupe9-svc
  namespace: groupe9-alone
spec:
  selector:
    app: groupe9-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9500
  type: LoadBalancer

